#!/usr/bin/env python3
import sys
from subprocess import call

if __name__ == "__main__":
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
    
    if cmd == "deploy":
        call(["cd", "app"])
        call(["lein", "uberwar"])
        call(["lein", "beanstalk", "deploy", "development", "target/ROOT.war"])
