DROP TABLE events;
DROP TABLE comments;
DROP TABLE subscriptions;
DROP TABLE followers;
DROP TABLE podcasts;
DROP TABLE messages;
DROP TABLE user_threads;
DROP TABLE threads CASCADE;
DROP TYPE genre;
DROP TYPE event;
