INSERT INTO podcasts
(name, genre, release_date, feed) VALUES 
('Fantasy Football Today Podcast', 'sports', CURRENT_TIMESTAMP, 'http://podcasts.cstv.com/feeds/fantasyfootball.xml'),
('Fantasy Baseball Today Podcast', 'sports', CURRENT_TIMESTAMP, 'http://podcasts.cstv.com/feeds/fantasybaseball.xml'),
('The Joe Rogan Experience', 'comedy', CURRENT_TIMESTAMP, 'http://joeroganexp.joerogan.libsynpro.com/rss'),
('Radiolab', 'science and medicine', CURRENT_TIMESTAMP, 'http://feeds.wnyc.org/radiolab?format=xml'),
('TED Radio Hour', 'culture', CURRENT_TIMESTAMP, 'http://www.npr.org/rss/podcast.php?id=510298'),
('Planet Money', 'business', CURRENT_TIMESTAMP, 'http://www.npr.org/rss/podcast.php?id=510289'),
('Wait Wait... Don''t Tell Me!', 'hobbies', CURRENT_TIMESTAMP, 'http://www.npr.org/rss/podcast.php?id=344098539'),
('Reply All', 'technology', CURRENT_TIMESTAMP, 'http://feeds.gimletmedia.com/hearreplyall'),
('Bill Burr''s Monday Morning Podcast', 'comedy', CURRENT_TIMESTAMP, 'http://billburr.libsyn.com/rss'),
('Science Vs', 'science and medicine', CURRENT_TIMESTAMP, 'http://feeds.soundcloud.com/users/soundcloud:users:154052752/sounds.rss'),
('Magic Lessons with Elizabeth Gilbert', 'arts', CURRENT_TIMESTAMP, 'http://magiclessons.libsyn.com/rss'),
('Sleep With Me', 'health', CURRENT_TIMESTAMP, 'http://sleepwithmepodcast.libsyn.com/rss'),
('World of Warcraft: The Tomb of Sargeras', 'hobbies', CURRENT_TIMESTAMP, 'http://bnetcmsus-a.akamaihd.net/cms/content_folder_media/s9/S9Y0JQTIA8YI1468967136536.xml'),
('Stuff You Missed in History Class', 'education', CURRENT_TIMESTAMP, 'http://www.howstuffworks.com/podcasts/stuff-you-missed-in-history-class.rss'),
('Modern Love', 'relationships', CURRENT_TIMESTAMP, 'http://feeds.wbur.org/modernlove/podcast?feed=podcast'),
('Unexplained', 'education', CURRENT_TIMESTAMP, 'http://rss.acast.com/unexplained'),
('The Nerdist', 'comedy', CURRENT_TIMESTAMP, 'http://nerdist.libsyn.com/rss'),
('The Tim Farris Show', 'business', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/thetimferrissshow?format=xml'),
('99% Invisible', 'education', CURRENT_TIMESTAMP, 'http://feeds.99percentinvisible.org/99percentinvisible'),
('Welcome to Nightvale', 'comedy', CURRENT_TIMESTAMP, 'http://nightvale.libsyn.com/rss'),
('Code Switch', 'news and politics', CURRENT_TIMESTAMP, 'http://www.npr.org/rss/podcast.php?id=510312'),
('Jalen & Jacoby', 'sports', CURRENT_TIMESTAMP, 'http://www.espn.com/espnradio/feeds/rss/podcast.xml?id=9545077'),
('First Take', 'sports', CURRENT_TIMESTAMP, 'http://www.espn.com/espnradio/podcast/feeds/itunes/podCast?id=6247496'),
('Call Chelsea Peretti', 'comedy', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/CallChelseaPeretti?format=xml'),
('Build Your Tribe', 'business', CURRENT_TIMESTAMP, 'http://chalenejohnson.libsyn.com/rss'),
('The Scumbag!', 'culture', CURRENT_TIMESTAMP, 'http://feeds.soundcloud.com/users/soundcloud:users:232616847/sounds.rss'),
('Slate''s Political Gabfest', 'news and politics', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/SlatePoliticalGabfest?format=xml'),
('The Art of Charm', 'relationships', CURRENT_TIMESTAMP, 'http://theartofcharmpodcast.theartofcharm.libsynpro.com/rss'),
('The EntreLeadership Podcast', 'business', CURRENT_TIMESTAMP, 'http://entreleadershippodcast.ramsey.libsynpro.com/rss'),
('The Art of Manliness', 'culture', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/artofmanlinesspodcast'),
('JapanesePod101', 'education', CURRENT_TIMESTAMP, 'http://www.japanesepod101.com/wp/wp-feed-audio.php'),
('You Need A Budget', 'education', CURRENT_TIMESTAMP, 'http://youneedabudget.libsyn.com/rss'),
('This Week In Law', 'government', CURRENT_TIMESTAMP, 'http://feeds.twit.tv/twil.xml'),
('Chairborne Commandos', 'government', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/ChairborneCommandos'),
('Oyez', 'government', CURRENT_TIMESTAMP, 'https://api.oyez.org/podcasts/oral-arguments/2015'),
('Metropocalypse', 'government', CURRENT_TIMESTAMP, 'http://wamu.org/rss/npr/metropocalypse.rss'),
('Savage Lovecast', 'relationships', CURRENT_TIMESTAMP, 'http://savagelove.libsyn.com/rss'),
('Sex With Emily', 'relationships', CURRENT_TIMESTAMP, 'http://emilymorse.libsyn.com/rss'),
('Ben Greenfield Fitness', 'health', CURRENT_TIMESTAMP, 'http://bengreenfieldfitness.libsyn.com/rss'),
('Gospel In Life', 'religion', CURRENT_TIMESTAMP, 'https://ginl-podcast.s3.amazonaws.com/0_Resources/Timothy_Keller_Podcasts.xml'),
('Daily Hope with Rick Warren', 'religion', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/DailyHopeWithRickWarrenPodcast?format=xml'),
('The Liturgists Podcast', 'religion', CURRENT_TIMESTAMP, 'http://theliturgists.podbean.com/feed/'),
('Car Talk', 'hobbies', CURRENT_TIMESTAMP, 'http://www.npr.org/rss/podcast.php?id=510208'),
('The Woodworking Podcast', 'hobbies', CURRENT_TIMESTAMP, 'http://www.thewoodworkingpodcast.com/feed/'),
('Drunks and Dragons', 'hobbies', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/DnDPodcast?format=xml'),
('Nursing Mnemonics Show by NRSNG', 'science and medicine', CURRENT_TIMESTAMP, 'https://www.nrsng.com/feed/mnemonics-podcast/'),
('Data Skeptic', 'science and medicine', CURRENT_TIMESTAMP, 'http://dataskeptic.libsyn.com/rss'),
('MedMaster Podcast', 'science and medicine', CURRENT_TIMESTAMP, 'https://www.nrsng.com/feed/motd/'),
('Planetary Radio', 'science and medicine', CURRENT_TIMESTAMP, 'http://www.planetary.org/multimedia/podcasts/planetary-radio-podcast-rss.xml'),
('Science Weekly', 'science and medicine', CURRENT_TIMESTAMP, 'https://www.theguardian.com/science/series/science/podcast.xml'),
('Remarkable Lives. Tragic Deaths.', 'culture', CURRENT_TIMESTAMP, 'http://feeds.soundcloud.com/users/soundcloud:users:242596778/sounds.rss'),
('The Dinner Party', 'culture', CURRENT_TIMESTAMP, 'http://feeds.feedburner.com/dinnerpartydownload'),
('Call Your Girlfriend', 'culture', CURRENT_TIMESTAMP, 'http://rss.acast.com/callyourgirlfriend'),
('Software Engineering Daily', 'technology', CURRENT_TIMESTAMP, 'http://softwareengineeringdaily.com/feed/podcast/'),
('Talk Python to Me', 'technology', CURRENT_TIMESTAMP, 'https://talkpython.fm/episodes/rss'),
('Startup School Radio', 'technology', CURRENT_TIMESTAMP, 'http://feeds.soundcloud.com/users/soundcloud:users:150759713/sounds.rss'),
('Learn To Code With Me', 'technology', CURRENT_TIMESTAMP, 'http://learntocodewithme.libsyn.com/rss');
